// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load environment variables from .env.local
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // Use DIRECT_URL (Session Pooler, port 5432) for migrations:
    // - Avoids IPv6 issue on Vercel (direct connection db.*.supabase.co uses IPv6)
    // - Supports advisory locks (unlike Transaction Pooler port 6543)
    url: process.env["DIRECT_URL"],
  },
});

